//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsInteracao.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsInteracao.ServiceReference1.HelloWorldResponse HelloWorld(WindowsFormsInteracao.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsInteracao.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WindowsFormsInteracao.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name MeuMetodoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MeuMetodo", ReplyAction="*")]
        WindowsFormsInteracao.ServiceReference1.MeuMetodoResponse MeuMetodo(WindowsFormsInteracao.ServiceReference1.MeuMetodoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MeuMetodo", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsInteracao.ServiceReference1.MeuMetodoResponse> MeuMetodoAsync(WindowsFormsInteracao.ServiceReference1.MeuMetodoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsInteracao.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsInteracao.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsInteracao.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsInteracao.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MeuMetodoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MeuMetodo", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsInteracao.ServiceReference1.MeuMetodoRequestBody Body;
        
        public MeuMetodoRequest() {
        }
        
        public MeuMetodoRequest(WindowsFormsInteracao.ServiceReference1.MeuMetodoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MeuMetodoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int opcao;
        
        public MeuMetodoRequestBody() {
        }
        
        public MeuMetodoRequestBody(int opcao) {
            this.opcao = opcao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MeuMetodoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MeuMetodoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsInteracao.ServiceReference1.MeuMetodoResponseBody Body;
        
        public MeuMetodoResponse() {
        }
        
        public MeuMetodoResponse(WindowsFormsInteracao.ServiceReference1.MeuMetodoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MeuMetodoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MeuMetodoResult;
        
        public MeuMetodoResponseBody() {
        }
        
        public MeuMetodoResponseBody(string MeuMetodoResult) {
            this.MeuMetodoResult = MeuMetodoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsInteracao.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsInteracao.ServiceReference1.WebService1Soap>, WindowsFormsInteracao.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsInteracao.ServiceReference1.HelloWorldResponse WindowsFormsInteracao.ServiceReference1.WebService1Soap.HelloWorld(WindowsFormsInteracao.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsInteracao.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsInteracao.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsInteracao.ServiceReference1.HelloWorldRequestBody();
            WindowsFormsInteracao.ServiceReference1.HelloWorldResponse retVal = ((WindowsFormsInteracao.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsInteracao.ServiceReference1.HelloWorldResponse> WindowsFormsInteracao.ServiceReference1.WebService1Soap.HelloWorldAsync(WindowsFormsInteracao.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsInteracao.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsInteracao.ServiceReference1.HelloWorldRequest inValue = new WindowsFormsInteracao.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsFormsInteracao.ServiceReference1.HelloWorldRequestBody();
            return ((WindowsFormsInteracao.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsInteracao.ServiceReference1.MeuMetodoResponse WindowsFormsInteracao.ServiceReference1.WebService1Soap.MeuMetodo(WindowsFormsInteracao.ServiceReference1.MeuMetodoRequest request) {
            return base.Channel.MeuMetodo(request);
        }
        
        public string MeuMetodo(int opcao) {
            WindowsFormsInteracao.ServiceReference1.MeuMetodoRequest inValue = new WindowsFormsInteracao.ServiceReference1.MeuMetodoRequest();
            inValue.Body = new WindowsFormsInteracao.ServiceReference1.MeuMetodoRequestBody();
            inValue.Body.opcao = opcao;
            WindowsFormsInteracao.ServiceReference1.MeuMetodoResponse retVal = ((WindowsFormsInteracao.ServiceReference1.WebService1Soap)(this)).MeuMetodo(inValue);
            return retVal.Body.MeuMetodoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsInteracao.ServiceReference1.MeuMetodoResponse> WindowsFormsInteracao.ServiceReference1.WebService1Soap.MeuMetodoAsync(WindowsFormsInteracao.ServiceReference1.MeuMetodoRequest request) {
            return base.Channel.MeuMetodoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsInteracao.ServiceReference1.MeuMetodoResponse> MeuMetodoAsync(int opcao) {
            WindowsFormsInteracao.ServiceReference1.MeuMetodoRequest inValue = new WindowsFormsInteracao.ServiceReference1.MeuMetodoRequest();
            inValue.Body = new WindowsFormsInteracao.ServiceReference1.MeuMetodoRequestBody();
            inValue.Body.opcao = opcao;
            return ((WindowsFormsInteracao.ServiceReference1.WebService1Soap)(this)).MeuMetodoAsync(inValue);
        }
    }
}
